### ISSUE TITLE
Use a different dockerhub account

### ISSUE THREAD

**Issue by ThomasThelen** [DataONEorg/gnis-deployment#11]
GraphDB, the triplifier, and the webapp are al using my personal dockerhub account; we should switch these to somewhere more official.

**Comment by mbjones** [comment]
One possibility is to not use dockerhub at all, and instead use the GitHub package repository to store images (either on our public repo or on our GHE server). I tried it with some GitHub actions and it was really easy. Haven't tried it from k8s but maybe it would be similar?

**Comment by ThomasThelen** [comment]
I _think_ I'm reading the [billing page](https://docs.github.com/en/billing/managing-billing-for-github-packages/about-billing-for-github-packages) correctly - the allocated resources for free and pro accounts are pretty low.

500mb disk space and 1gb of transfer per month for free
2gb disk space and 10GB of transfer per month for pro

Additionally, the storage & network transfer are added into the GitHub Actions quota.

We had talked in the past about deploying something along the lines of docker registry; I think that GHE package registry is a pretty nice alternative since it's bundled within the GitHub deployment and we can publish more than _just_ docker images. We'd also have much much more storage, image management becomes less of a hassle with different accounts,  and we won't have any direct costs. It also gives us a little protection against overly relying on GitHub's service which might fluctuate in free features.

**Comment by mbjones** [comment]
I'd asked nick to get GHE working for Actions and the package registry, but he ran into some issues with configuration of the S3 store IIRC. In any case, can we start with the public github.com package registry, and then if needed we can add or replace it with GHE registries, which might take a bit to set up?

Also note from the page: 
> GitHub Packages usage is free for public packages.
