### ISSUE TITLE
Slow Graph Export

### ISSUE THREAD

**Issue by ThomasThelen** [DataONEorg/gnis-deployment#13]
@amoeba noticed that the graph export is pretty slow. We might be able to speed it up by exporting to N-Triples instead of turtle.

**Comment by amoeba** [comment]
Since the data change rarely, we might also think up a way to just server a static dump in one format or another.

As a data point for the current speed of the /data endpoint, I get an order of magnitude increase in transfer rate (~300KB/s to ~3000KB/s) when dumping the entire graph as a CSV via SPARQL compared to the /data endpoint so there must be a way to make /data faster.

**Comment by ThomasThelen** [comment]
Changing the export type to n-triples I get download speeds of ~2500k, which is a huge improvement over the ttl format performance. I think that this is fast enough for downloading the roughly 2.5 GB of data. This has been deployed on stage and can be tested there.

**Comment by amoeba** [comment]
That's great to hear. I did just try it (https://stage.gnis-ld.org/data) and only got 250k/s. I tried again from an NCEAS host and the request is actually hanging right now. The second issue is kinda weird.

Edit: The request finally returns a 504.

**Comment by ThomasThelen** [comment]
With the image management issues I was having over, this issue should be testable on stage again (sorry for having to test twice). The speed is a little over 1 MB/S on my connection (which is top speeds for my provider).

**Comment by amoeba** [comment]
Looks pretty good here: Varying from 5-10MB/s (average 6MB/s) from campus. Thanks @ThomasThelen. That speed bump makes it much more practical to export everything. I did notice the size of the exported NTriples file is now 5.4G but still 32,949,518 triples. Could we update the text on the home page to match?

**Comment by ThomasThelen** [comment]
Good catch - updated on stage, shown below
<img width="1330" alt="Screen Shot 2021-12-08 at 10 46 13 AM" src="https://user-images.githubusercontent.com/9289652/145265993-c46cc858-1f6c-4c2c-b9d4-fc66d5528cb2.png">

**Comment by amoeba** [comment]
Great, thanks.
