### ISSUE TITLE
Investigate incomplete responses and 504s

### ISSUE THREAD

**Issue by amoeba** [DataONEorg/gnis-deployment#14]
While testing slow graph export today in https://github.com/DataONEorg/gnis-deployment/issues/13#issuecomment-987519671, I also ended producing some odd behavior from the application that might be a crash.

While trying to dump data via SPARQL like:

```
curl -v 'https://gnis-ld.org/sparql'   --data-raw 'query=PREFIX+rdf%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%3E%0D%0APREFIX+ago%3A+%3Chttp%3A%2F%2Fawesemantic-geo.link%2Fontology%2F%3E%0D%0APREFIX+geosparql%3A+%3Chttp%3A%2F%2Fwww.opengis.net%2Font%2Fgeosparql%23%3E%0D%0A%0D%0Aselect+%3Ffeature+%3Fwkt+where+%7B%0D%0A++++%3Ffeature+ago%3Ageometry+%3Fgeometry+.%0D%0A++++%3Fgeometry+geosparql%3AasWKT+%3Fwkt+.+++%0D%0A%7D%0D%0A&infer=true&sameAs=true&Accept=text%2Fcsv&authToken='
```

I see two things:

1. An incomplete response that either hangs up or just hangs. This worked against stage last week without issues. It takes a while so just let the curl command run for a few minutes.
2. gnis-ld.org starts throwing 504s right after the hang or hangup. It seems to eventually heal itself so could this be a container crash? We should be able to reproduce with the curl command above.

Note: It seems like hitting /data also produces this.

I think it's reasonable to assume someone else might do something similar to what I've done and we don't want the service to go down.

**Comment by ThomasThelen** [comment]
Retesting this on production and stage it's looking fine on my end. There was the issue on the k8s-node-3 where resources were being overly consumed, possibly around the same time this was tested which would explain the hangups.

**Comment by amoeba** [comment]
Thanks @ThomasThelen.

@nickatnceas mentioned:

> k8s-node-3 (docker-ucsb-7) has a load of >450, and is killing processes via the kernel’s OOM killer

So that makes a little more sense. I tested again and wasn't able to reproduce so that's probably what it was.
